# Generated by Django 5.2.13 on 2026-04-14 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_editora_cidade_editora_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='autores',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
