# Generated by Django 5.2.13 on 2026-04-14 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_livro_preco'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livro',
            name='autores',
        ),
        migrations.AddField(
            model_name='livro',
            name='autores',
            field=models.ManyToManyField(blank=True, null=True, related_name='livros', to='core.autor'),
        ),
    ]
