# Generated by Django 5.2.13 on 2026-04-14 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_livro_autores_livro_autores'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livro',
            name='autores',
        ),
        migrations.AddField(
            model_name='livro',
            name='autores',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
